---
services:
    nginx-mailcow:
      networks:
        traefik-server:
          aliases:
            - nginx
      labels:
        traefik.enable: "true"
        traefik.http.routers.mailcow-web.rule: "Host(`${MAILCOW_HOSTNAME}`)"
        traefik.http.routers.mailcow-web.service: "mailcow-web-service"
        traefik.http.routers.mailcow-web.tls: "true"
        traefik.http.routers.mailcow-web.tls.certresolver: "le"
        traefik.http.services.mailcow-web.loadbalancer.server.port: "${HTTP_PORT}"
        traefik.http.routers.mailcow-web.entrypoints: "https"
        traefik.docker.network: "traefik-server"
        # traefik.http.middlewares.mailcow-https-redirect.redirectscheme.scheme: "https"
        # traefik.http.middlewares.mailcow-https-redirect.redirectscheme.permanent: "true"
        # traefik.http.routers.mailcow-web.middlewares: "mailcow-https-redirect"
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT}"]
        interval: 30s
        timeout: 10s
        retries: 3

    postfix-mailcow:
      ports: []
      networks:
        traefik-server:
          aliases:
            - postfix
      labels:
        traefik.enable: "true"
        traefik.tcp.routers.postfix-smtp.rule: "HostSNI(`*`)"
        traefik.tcp.routers.postfix-smtp.service: "postfix-smtp-service"
        traefik.tcp.routers.postfix-smtp.entrypoints: "smtp"
        traefik.tcp.services.postfix-smtp.loadbalancer.server.port: "25"
        traefik.tcp.routers.postfix-smtps.rule: "HostSNI(`*`)"
        traefik.tcp.routers.postfix-smtps.service: "postfix-smtps-service"
        traefik.tcp.routers.postfix-smtps.entrypoints: "smtps"
        traefik.tcp.services.postfix-smtps.loadbalancer.server.port: "465"
        traefik.tcp.routers.postfix-submission.rule: "HostSNI(`*`)"
        traefik.tcp.routers.postfix-submission.service: "postfix-submission-service"
        traefik.tcp.routers.postfix-submission.entrypoints: "submission"
        traefik.tcp.services.postfix-submission.loadbalancer.server.port: "587"

    dovecot-mailcow:
      networks:
        traefik-server:
          aliases:
            - dovecot
      labels:
        traefik.enable: "true"
        traefik.tcp.routers.dovecot-imap.rule: "HostSNI(`*`)"
        traefik.tcp.routers.dovecot-imap.service: "dovecot-imap-service"
        traefik.tcp.routers.dovecot-imap.entrypoints: "imap"
        traefik.tcp.services.dovecot-imap.loadbalancer.server.port: "143"
        traefik.tcp.routers.dovecot-imaps.rule: "HostSNI(`*`)"
        traefik.tcp.routers.dovecot-imaps.service: "dovecot-imaps-service"
        traefik.tcp.routers.dovecot-imaps.entrypoints: "imaps"
        traefik.tcp.services.dovecot-imaps.loadbalancer.server.port: "993"
        
    certdumper:
        image: ghcr.io/kereis/traefik-certs-dumper
        command: --restart-containers ${COMPOSE_PROJECT_NAME}-postfix-mailcow-1,${COMPOSE_PROJECT_NAME}-nginx-mailcow-1,${COMPOSE_PROJECT_NAME}-dovecot-mailcow-1
        network_mode: none
        volumes:
          - traefik-server-certificates:/traefik:ro
          - ./data/assets/ssl/:/output:rw
          - /var/run/docker.sock:/var/run/docker.sock:ro
        restart: always
        environment:
          - DOMAIN=${MAILCOW_HOSTNAME}

networks:
  traefik-server:
    external: true

volumes:
  traefik-server-certificates:
    external: true
    name: traefik-servermanager_traefik-server-certificates